[workspace]
version = "0.0.1"
resolver = "2"
members = [
  # runtime + WASM components
  "bin/app",
  "bin/host",
  # "runtime/interface",
  # "runtime/native",

  # core components
  # "components/persona",
  # "components/persona/core",
  # "components/persona/methods",
  # "components/persona/methods/guest",

  # system components
  # "components/crypto",
  # "components/domo",
  # "components/websql",
  # "components/webview",
  # "components/servo",
  # "components/wgpu",
]
exclude = [
]

[workspace.package]
version = "0.0.1"
authors = ["sunny-g"]
license = "MIT OR Apache-2.0"
homepage = "https://github.com/datalove-app/datalove"
repository = "https://github.com/datalove-app/datalove"
keywords = ["p2p", "webassembly"]
edition = "2021"
rust-version = "1.70"

[workspace.dependencies]
futures = { version = "0.3", default-features = false }
# futures-channel = { version = "0.3", default-features = false }
# futures-util = { version = "0.3", default-features = false }
serde = { version = "1.0", default-features = false }
thiserror = { version = "1.0", default-features = false }
tokio = { version = "1.28", default-features = false }
tracing = { version = "0.1", default-features = false }
tracing-futures = { version = "0.2", default-features = false }
tracing-subscriber = { version = "0.2", default-features = false }

# lean4-rs = { path = "vendor/lean4-rs" }
# lean-sitter-witx = { path = "vendor/lean-sitter-witx" }
# lunatic-runtime = { path = "vendor/lunatic" }
# lurk = { path = "vendor/lurk-rs" }
# wasm-bpf-rs = { path = "vendor/wasm-bpf/runtime/wasm-bpf-rs" }

# # wasm runtime
wasmer = { version = "4.2", default-features = false }
wasmer-wasix = { version = "0.14", default-features = false }
# wasmer-wasix-experimental-io-devices = { version = "0.10", default-features = false }
# # wai
# wai-bindgen-rust = { version = "0.2.3", default-features = false }
# wai-bindgen-wasmer = { version = "0.10", default-features = false }

# wasm (host) components
# wac-crypto = { path = "rust/runtime/components/crypto", default-features = false }
# wac-web-sys = { path = "rust/runtime/web-sys", default-features = false }
# wac-wgpu = { path = "rust/runtime/components/wgpu", default-features = false }

# crypto, zk
borsh = { version = "1.0.0-alpha.5", default-features = false }
cid = { version = "0.10", default-features = false }
digest = { version = "0.10", default-features = false }
ed25519-dalek = { version = "2.0", default-features = false }
# k256 = { git = "https://github.com/risc0/rustcrypto-elliptic-curves", branch = "risc0" }
# pqc_kyber = {version = "0.7.1", default-features = false }
merkle-log = { version = "0.0.9", default-features = false }
sha2 = { version = "0.10", default-features = false }
veilid-core = { version = "0.2.2", default-features = false, features = [
  "enable-crypto-vld0",
  # "rt-tokio",
] }

risc0-build = { version = "0.18", default-features = false }
risc0-zkvm = { version = "0.18", default-features = false }

[patch.crates-io]
# merkle-log = { path = "vendor/merkle-log" }
# rusqlite = { version = "0.29", default-features = false, features = ["bundled-sqlcipher"] }

# app
blitz = { path = "vendor/blitz" }
blitz-core = { path = "vendor/blitz/blitz-core" }
dioxus = { git = "https://github.com/dioxuslabs/dioxus" }
dioxus-html = { git = "https://github.com/dioxuslabs/dioxus" }
dioxus-native-core = { git = "https://github.com/dioxuslabs/dioxus" }

# # wasm
# wasmer = { path = "rust/packages/wasmer/lib/api" }
# wasmer-types = { path = "rust/packages/wasmer/lib/types" }
# wasmer-wasix = { path = "rust/packages/wasmer/lib/wasix" }
# wasmer-wasix-experimental-io-devices = { path = "rust/packages/wasmer/lib/wasi-experimental-io-devices" }
# wasmer-wasix-types = { path = "rust/packages/wasmer/lib/wasi-types" }
# # wai
# wai-bindgen-rust = { path = "rust/packages/wai/crates/rust-wasm" }
# wai-bindgen-rust-impl = { path = "rust/packages/wai/crates/rust-wasm-impl" }
# wai-bindgen-wasmer = { path = "rust/packages/wasmer/lib/wai-bindgen-wasmer" }
# wai-bindgen-gen-wasmer = { path = "rust/packages/wai/crates/gen-wasmer" }
# wai-bindgen-wasmer-impl = { path = "rust/packages/wai/crates/wasmer-impl" }

# wasm-bindgen = { path = "rust/packages/wasm-bindgen" }
# wasi-crypto = { path = "vendor/wasi-crypto/implementations/hostcalls/rust" }

# wgpu = { path = "rust/runtime/components/wgpu/wgpu/wgpu" }
# wgpu-core = { path = "rust/runtime/components/wgpu/wgpu/wgpu-core" }
# wgpu-hal = { path = "rust/runtime/components/wgpu/wgpu/wgpu-hal" }
# wgpu-types = { path = "rust/runtime/components/wgpu/wgpu/wgpu-types" }
# wgpu-native = { path = "rust/packages/wgpu-native" }

# [patch.'https://github.com/sunny-g/wgpu']
# wgpu = { path = "rust/runtime/components/wgpu/wgpu/wgpu" }
# wgpu-core = { path = "rust/runtime/components/wgpu/wgpu/wgpu-core" }
# wgpu-hal = { path = "rust/runtime/components/wgpu/wgpu/wgpu-hal" }
# wgpu-types = { path = "rust/runtime/components/wgpu/wgpu/wgpu-types" }

# [patch.'https://github.com/gfx-rs/wgpu-native']
# wgpu-native = { path = "rust/packages/wgpu-native" }

# [profile.dev]
# opt-level = 3

# [profile.dev-build-override]
# opt-level = 3

# [profile.release]
# debug = 1
# lto = true

# [profile.release.build-override]
# opt-level = 3
