[package]
name = "datalove-app"
version.workspace = true
edition.workspace = true

[[bin]]
name = "datalove_browser"
path = "bin/main.rs"

[dependencies]
datalove-host = { path = "../host" }

# general
tokio = { workspace = true, features = ["full"] }

# # wasm
# wasmer = { workspace = true }

# ui, windowing
blitz = { version = "0.1", default-features = false, features = [
  # "hot-reload"
] }
blitz-core = { version = "0.1", default-features = false, features = [] }
dioxus = { version = "0.4", default-features = false, features = [
  # "hot-reload"
  "html",
  "macro",
] }
# dioxus-html = { version = "0.4" }
# dioxus-hot-reload = { version = "0.4" }
dioxus-native-core = { version = "0.4", default-features = false, features = [
  # "hot-reload"
  "dioxus"
] }
tao = { version = "0.20", default-features = false, features = [
] }
# wry = { version = "0.29", default-features = false, features = [
#   # "fullscreen",
#   # "transparent",
#   # "tao",
# ] }
